# Docker Compose file for a Baikal server with MariaDB 5
# Based on issue https://github.com/ckulka/baikal-docker/issues/10

version: '2'
services:
  baikal:
    image: ckulka/baikal:experimental-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - baikal:/var/www/baikal/Specific

  db:
    image: mariadb:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adalovelace
      MYSQL_DATABASE: baikal
      MYSQL_USER: baikal
      MYSQL_PASSWORD: ilovecookies
    volumes:
      - db:/var/lib/mysql

volumes:
  baikal:
  db:
