# See
# - https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
# - https://docs.github.com/en/actions/learn-github-actions/contexts
# - https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
name: docker build

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/docker-build.yml
      - "*.dockerfile"
      - files/*
  release:
    types:
      - published

jobs:
  build_apache:
    name: Build Apache variant
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # See https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # See https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # See https://github.com/docker/login-action
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build Apache httpd images
      - name: Build and push experimental image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          file: apache.dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/386
          push: true
          tags: |
            ckulka/baikal:experimental-apache
            ckulka/baikal:experimental

      - name: Build and push release image
        if: github.event_name == 'release'
        uses: docker/build-push-action@v2
        with:
          file: apache.dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/386
          push: true
          tags: |
            ckulka/baikal:${{ github.ref_name }}-apache
            ckulka/baikal:${{ github.ref_name }}
            ckulka/baikal:apache
            ckulka/baikal:latest

  build_apache_php80:
    name: Build Apache variant (PHP 8.0)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # See https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # See https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # See https://github.com/docker/login-action
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build Apache httpd images
      - name: Build and push experimental image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          file: apache-php8.0.dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/386
          push: true
          tags: |
            ckulka/baikal:experimental-apache-php8.0
            ckulka/baikal:experimental-php8.0

      - name: Build and push release image
        if: github.event_name == 'release'
        uses: docker/build-push-action@v2
        with:
          file: apache-php8.0.dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/386
          push: true
          tags: |
            ckulka/baikal:${{ github.ref_name }}-apache-php8.0
            ckulka/baikal:${{ github.ref_name }}-php8.0
            ckulka/baikal:apache-php8.0
            ckulka/baikal:latest-php8.0

  build_nginx:
    name: Build nginx variant
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # See https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # See https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # See https://github.com/docker/login-action
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build nginx images
      - name: Build and push experimental image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          file: nginx.dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/386
          push: true
          tags: ckulka/baikal:experimental-nginx

      - name: Build and push release image
        if: github.event_name == 'release'
        uses: docker/build-push-action@v2
        with:
          file: nginx.dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/386
          push: true
          tags: |
            ckulka/baikal:${{ github.ref_name }}-nginx
            ckulka/baikal:nginx

  build_nginx_php80:
    name: Build nginx variant (PHP 8.0)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # See https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # See https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # See https://github.com/docker/login-action
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build nginx images
      - name: Build and push experimental image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          file: nginx-php8.0.dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/386
          push: true
          tags: ckulka/baikal:experimental-nginx-php8.0

      - name: Build and push release image
        if: github.event_name == 'release'
        uses: docker/build-push-action@v2
        with:
          file: nginx-php8.0.dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/386
          push: true
          tags: |
            ckulka/baikal:${{ github.ref_name }}-nginx-php8.0
            ckulka/baikal:nginx-php8.0
